---
title: "このサイトについて"
date: 12/26/2023
date-modified: 01/08/2023
abstract: ホームページ
---

# サイトの目的
　初めまして！「優月の生物統計学ノート」に来訪いただきありがとうございます。優月と申します。  
　このサイトでは医学に興味を持ったデータサイエンティストが、生物統計学の知識や実装を学んだノートを置いていきます。主な内容は以下を想定しています(そんなに医学してないな…w)。

- 数学(主に統計学)
- データ解析
- 機械学習
- プログラミング

どうぞよろしくお願い致します。

---

# 筆者の経歴
- 熊本県で生まれ育つ
- 国立大学の数学科を卒業
    - 解析学(微分積分学)を中心に数学理論を学ぶ
- 国立大学院の生命科学専攻を修了
    - Wetな手法でエピジェネティクスと初期発生に関する研究を行う
    - 定量化の方法としては画像解析系の技術を多く学ぶ
- 受託分析会社でデータサイエンティストとして勤務
    - データ利活用を目的としたコンサルテーションを担当
    - BIエンジニアリング, AIエンジニアリング, データ基盤作成, データ分析業を幅広く学ぶ
    - プロジェクトリーダーを経験
- **医療系ベンチャー企業のAIエンジニアとして勤務 ← Now**
    - 医療機器に組み込む疾患予測モデルの構築
    - 社内データ基盤の整備
    - 臨床研究におけるデータ解析を担当

---

# Enjoy Quarto!
　このサイトは全て[Quarto](https://quarto.org/)言語で記述しております。Quartoはこのようにウェブサイトを作れる他、分析レポートを作成したりダッシュボードも作成できる物凄くポテンシャルを感じるプログラミング言語です。是非皆さんも使ってみてください!

---

# 免責事項

- 本サイトに掲載されている情報は、正確である保証はありません。
- 本サイトに掲載されている情報は、私個人の見解である。所属機関を代表する見解ではありません。
- 本サイトを利用して、あなたに損害が生じても、一切責任を負いません。
- 本サイトのコンテンツは、予告なく変更や公開の取り消しする場合があります。

---

# ライセンス

## ブログ内のコンテンツ
本サイトにおける各エントリの文章や画像などのコンテンツは[クリエイティブ・コモンズ・ライセンス](https://creativecommons.org/licenses/by/4.0/deed.ja)を適応します。

## ブログ内サンプルコードのライセンス
ブログ内で書いているコードに関しては例外的にMIT Licenceを適応します。

:::{.callout-note collapse="true"}
## MIT License

Copyright 2023 優月

以下に定める条件に従い、本ソフトウェアおよび関連文書のファイル（以下「ソフトウェア」）の複製を取得するすべての人に対し、ソフトウェアを無制限に扱うことを無償で許可します。これには、ソフトウェアの複製を使用、複写、変更、結合、掲載、頒布、サブライセンス、および/または販売する権利、およびソフトウェアを提供する相手に同じことを許可する権利も無制限に含まれます。

上記の著作権表示および本許諾表示を、ソフトウェアのすべての複製または重要な部分に記載するものとします。

ソフトウェアは「現状のまま」で、明示であるか暗黙であるかを問わず、何らの保証もなく提供されます。ここでいう保証とは、商品性、特定の目的への適合性、および権利非侵害についての保証も含みますが、それに限定されるものではありません。 作者または著作権者は、契約行為、不法行為、またはそれ以外であろうと、ソフトウェアに起因または関連し、あるいはソフトウェアの使用またはその他の扱いによって生じる一切の請求、損害、その他の義務について何らの責任も負わないものとします。
:::